apiVersion: v1
data:
    mapRoles: |
        - groups:
          - system:bootstrappers
          - system:nodes
          rolearn: arn:aws:iam::747044263487:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LPBA7KB5AVGY
          username: system:node:{{EC2PrivateDNSName}}
        - groups:
          - system:masters
          rolearn: arn:aws:iam::747044263487:role/UdacityFlaskDeployCBKubectlRole
          username: build
kind: ConfigMap
metadata:
    creationTimestamp: "2022-07-22T10:05:46Z"
    name: aws-auth
    namespace: kube-system
    resourceVersion: "1618"
    uid: 264e46f7-e150-4ce8-a350-e6ef73f2d7b7
